### ISSUE TITLE
Implementare l'incantesimo "Arrocco"

### ISSUE THREAD

**Issue by ViuCoding** [biagiocaldararo/ChessGame#2]
Nel regno di Codexia, Biagio, il geniale sviluppatore, evocò l'incantesimo "Arrocco" per salvare il re Erisdar. Il re si teletrasportò dietro una torre, trasformata in drago, respingendo le forze oscure della regina Morgath.

**Comment by biagiocaldararo** [comment]
ci sto lavorando, dammi un attimo

**Comment by biagiocaldararo** [comment]
arrocco completato

**Comment by biagiocaldararo** [comment]
arrocco completato

**Comment by biagiocaldararo** [comment]
arrocco completato
